### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by ChatBotMatt** [RossBrunton/BMAT#14]
Also, searches should be case INsensitive.

**Comment by RossBrunton** [comment]
https://code.djangoproject.com/ticket/9682

This is a bug in Django, which they don't seem to want to fix, annoyingly.

**Comment by RossBrunton** [comment]
Right. I changed the collation on the database to a default case insensitive one... I'm not sure if it's actually supposed to be like that by default. It seems to work, but it may cause problems elsewhere... Hmm...
